"""
AI Career Recommendation Engine — Master Dataset
100+ skills · 80 job roles · Rich metadata for deep analytics
"""

JOB_ROLES_DB = [
    # ─── AI / ML ───────────────────────────────────────────────────────────────
    {
        "id": 1,
        "title": "Data Scientist",
        "category": "AI/ML",
        "demand": 95,
        "salary_min": 12,
        "salary_max": 25,
        "salary": "₹12-25 LPA",
        "growth": "+22%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "machine learning",
            "statistics",
            "data analysis",
            "sql",
            "tensorflow",
            "scikit-learn",
            "pandas",
            "numpy",
            "data visualization",
            "deep learning",
            "nlp",
            "r",
            "jupyter",
            "feature engineering",
            "model evaluation",
            "hypothesis testing",
            "bayesian statistics",
        ],
        "description": "Derive insights from complex data to drive business decisions.",
        "tools": ["Python", "Jupyter", "Tableau", "PowerBI", "Spark"],
        "certifications": [
            "Google Cloud Professional Data Engineer",
            "AWS ML Specialty",
        ],
    },
    {
        "id": 2,
        "title": "ML Engineer",
        "category": "AI/ML",
        "demand": 98,
        "salary_min": 15,
        "salary_max": 35,
        "salary": "₹15-35 LPA",
        "growth": "+28%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "machine learning",
            "deep learning",
            "tensorflow",
            "pytorch",
            "model deployment",
            "mlops",
            "docker",
            "kubernetes",
            "cloud",
            "api",
            "data pipelines",
            "cuda",
            "onnx",
            "triton",
            "feature store",
            "a/b testing",
            "model monitoring",
            "distributed training",
        ],
        "description": "Build and deploy scalable machine learning systems in production.",
        "tools": ["MLflow", "Kubeflow", "Seldon", "BentoML", "FastAPI"],
        "certifications": ["AWS ML Specialty", "Google Professional ML Engineer"],
    },
    {
        "id": 3,
        "title": "NLP Engineer",
        "category": "AI/ML",
        "demand": 93,
        "salary_min": 14,
        "salary_max": 30,
        "salary": "₹14-30 LPA",
        "growth": "+35%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "nlp",
            "machine learning",
            "deep learning",
            "bert",
            "transformers",
            "tensorflow",
            "pytorch",
            "text processing",
            "linguistics",
            "huggingface",
            "llm",
            "rag",
            "finetuning",
            "langchain",
            "vector databases",
            "prompt engineering",
            "semantic search",
            "question answering",
        ],
        "description": "Build language understanding systems and LLM-powered applications.",
        "tools": ["HuggingFace", "LangChain", "Pinecone", "OpenAI", "Weaviate"],
        "certifications": ["DeepLearning.AI NLP Specialization"],
    },
    {
        "id": 4,
        "title": "Computer Vision Engineer",
        "category": "AI/ML",
        "demand": 92,
        "salary_min": 13,
        "salary_max": 28,
        "salary": "₹13-28 LPA",
        "growth": "+24%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "computer vision",
            "deep learning",
            "opencv",
            "tensorflow",
            "pytorch",
            "image processing",
            "yolo",
            "cnns",
            "cuda",
            "object detection",
            "image segmentation",
            "3d vision",
            "slam",
            "augmented reality",
            "medical imaging",
            "video analytics",
            "generative models",
        ],
        "description": "Develop visual perception systems for images and video.",
        "tools": ["OpenCV", "PyTorch", "CUDA", "TensorRT", "Label Studio"],
        "certifications": ["NVIDIA Deep Learning Institute"],
    },
    {
        "id": 5,
        "title": "AI Research Scientist",
        "category": "AI/ML",
        "demand": 97,
        "salary_min": 20,
        "salary_max": 50,
        "salary": "₹20-50 LPA",
        "growth": "+40%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "python",
            "deep learning",
            "mathematics",
            "research",
            "tensorflow",
            "pytorch",
            "machine learning",
            "nlp",
            "computer vision",
            "statistics",
            "publications",
            "reinforcement learning",
            "transformers",
            "graph neural networks",
            "causal inference",
            "meta learning",
            "federated learning",
        ],
        "description": "Push the boundaries of AI with fundamental research.",
        "tools": ["JAX", "PyTorch", "LaTeX", "Weights & Biases", "Papers With Code"],
        "certifications": ["PhD preferred", "NeurIPS/ICML publications"],
    },
    {
        "id": 6,
        "title": "MLOps Engineer",
        "category": "AI/ML",
        "demand": 94,
        "salary_min": 14,
        "salary_max": 32,
        "salary": "₹14-32 LPA",
        "growth": "+32%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "mlops",
            "python",
            "docker",
            "kubernetes",
            "aws",
            "model deployment",
            "ci/cd",
            "monitoring",
            "data pipelines",
            "airflow",
            "mlflow",
            "bentoml",
            "weights & biases",
            "feature store",
            "data versioning",
            "model registry",
            "drift detection",
            "canary deployment",
            "model explainability",
        ],
        "description": "Streamline the ML lifecycle from experiment to production.",
        "tools": ["MLflow", "Kubeflow", "DVC", "Seldon", "Evidently AI"],
        "certifications": ["AWS ML Specialty", "CKA"],
    },
    {
        "id": 7,
        "title": "Generative AI Engineer",
        "category": "AI/ML",
        "demand": 99,
        "salary_min": 18,
        "salary_max": 45,
        "salary": "₹18-45 LPA",
        "growth": "+65%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "llm",
            "prompt engineering",
            "langchain",
            "vector databases",
            "rag",
            "finetuning",
            "huggingface",
            "openai",
            "stable diffusion",
            "gan",
            "diffusion models",
            "multimodal",
            "agents",
            "tool use",
            "context management",
            "evaluation frameworks",
            "guardrails",
        ],
        "description": "Build cutting-edge generative AI products and pipelines.",
        "tools": ["LangChain", "LlamaIndex", "OpenAI", "Anthropic", "Pinecone"],
        "certifications": ["DeepLearning.AI LangChain", "OpenAI Developer"],
    },
    {
        "id": 8,
        "title": "Reinforcement Learning Engineer",
        "category": "AI/ML",
        "demand": 88,
        "salary_min": 16,
        "salary_max": 40,
        "salary": "₹16-40 LPA",
        "growth": "+28%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "python",
            "reinforcement learning",
            "deep learning",
            "pytorch",
            "mathematics",
            "openai gym",
            "policy gradient",
            "q-learning",
            "mcts",
            "game theory",
            "simulation",
            "robotics",
            "control systems",
            "multi-agent systems",
            "imitation learning",
        ],
        "description": "Develop agents that learn through environment interaction.",
        "tools": ["OpenAI Gym", "Ray RLlib", "Stable Baselines", "MuJoCo"],
        "certifications": ["David Silver RL Course", "Spinning Up"],
    },
    # ─── Data ─────────────────────────────────────────────────────────────────
    {
        "id": 9,
        "title": "Data Engineer",
        "category": "Data",
        "demand": 91,
        "salary_min": 12,
        "salary_max": 28,
        "salary": "₹12-28 LPA",
        "growth": "+20%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "sql",
            "spark",
            "hadoop",
            "data pipelines",
            "aws",
            "kafka",
            "airflow",
            "etl",
            "databases",
            "cloud",
            "scala",
            "bigquery",
            "dbt",
            "snowflake",
            "flink",
            "data lake",
            "data warehouse",
            "delta lake",
        ],
        "description": "Design and build robust data infrastructure and pipelines.",
        "tools": ["Apache Spark", "Airflow", "dbt", "Snowflake", "BigQuery"],
        "certifications": ["Google Professional Data Engineer", "Databricks Certified"],
    },
    {
        "id": 10,
        "title": "Data Analyst",
        "category": "Data",
        "demand": 84,
        "salary_min": 6,
        "salary_max": 18,
        "salary": "₹6-18 LPA",
        "growth": "+15%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "sql",
            "excel",
            "python",
            "data visualization",
            "tableau",
            "powerbi",
            "statistics",
            "reporting",
            "dashboards",
            "business intelligence",
            "data cleaning",
            "pivot tables",
            "r",
            "looker",
            "google analytics",
        ],
        "description": "Transform raw data into actionable business insights.",
        "tools": ["Tableau", "Power BI", "Looker", "SQL", "Excel"],
        "certifications": ["Google Data Analytics", "Tableau Desktop Specialist"],
    },
    {
        "id": 11,
        "title": "Analytics Engineer",
        "category": "Data",
        "demand": 89,
        "salary_min": 10,
        "salary_max": 24,
        "salary": "₹10-24 LPA",
        "growth": "+25%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "sql",
            "dbt",
            "python",
            "data modeling",
            "snowflake",
            "bigquery",
            "data warehouse",
            "analytics",
            "git",
            "testing",
            "documentation",
            "business intelligence",
            "etl",
            "dagster",
            "metabase",
        ],
        "description": "Bridge the gap between data engineering and business analytics.",
        "tools": ["dbt", "Snowflake", "Metabase", "Looker", "Airflow"],
        "certifications": ["dbt Analytics Engineering Certification"],
    },
    {
        "id": 12,
        "title": "BI Developer",
        "category": "Data",
        "demand": 82,
        "salary_min": 8,
        "salary_max": 20,
        "salary": "₹8-20 LPA",
        "growth": "+12%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "sql",
            "powerbi",
            "tableau",
            "ssrs",
            "ssis",
            "data modeling",
            "dax",
            "mdx",
            "etl",
            "databases",
            "excel",
            "reporting",
            "kpi",
            "dashboards",
            "olap",
            "microsoft azure",
        ],
        "description": "Design and maintain interactive business intelligence dashboards.",
        "tools": ["Power BI", "Tableau", "SSRS", "SSAS", "SQL Server"],
        "certifications": ["Microsoft PL-300", "Tableau Desktop Specialist"],
    },
    # ─── Development ──────────────────────────────────────────────────────────
    {
        "id": 13,
        "title": "Backend Developer",
        "category": "Development",
        "demand": 88,
        "salary_min": 8,
        "salary_max": 20,
        "salary": "₹8-20 LPA",
        "growth": "+18%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "java",
            "python",
            "node.js",
            "sql",
            "rest api",
            "microservices",
            "docker",
            "git",
            "databases",
            "spring boot",
            "express",
            "postgresql",
            "redis",
            "graphql",
            "message queues",
            "authentication",
            "caching",
            "testing",
            "design patterns",
        ],
        "description": "Build scalable server-side applications and APIs.",
        "tools": ["Spring Boot", "FastAPI", "Express", "PostgreSQL", "Redis"],
        "certifications": ["Oracle Java SE", "AWS Developer Associate"],
    },
    {
        "id": 14,
        "title": "Frontend Developer",
        "category": "Development",
        "demand": 85,
        "salary_min": 7,
        "salary_max": 18,
        "salary": "₹7-18 LPA",
        "growth": "+16%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "javascript",
            "react",
            "html",
            "css",
            "typescript",
            "vue.js",
            "node.js",
            "git",
            "ui/ux",
            "responsive design",
            "webpack",
            "testing",
            "figma",
            "accessibility",
            "performance optimization",
            "pwa",
            "web components",
            "state management",
            "nextjs",
        ],
        "description": "Craft pixel-perfect, high-performance user interfaces.",
        "tools": ["React", "Next.js", "TypeScript", "Tailwind CSS", "Figma"],
        "certifications": ["Meta Front-End Developer", "Google UX Design"],
    },
    {
        "id": 15,
        "title": "Full Stack Developer",
        "category": "Development",
        "demand": 87,
        "salary_min": 9,
        "salary_max": 22,
        "salary": "₹9-22 LPA",
        "growth": "+18%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "javascript",
            "react",
            "node.js",
            "sql",
            "html",
            "css",
            "git",
            "rest api",
            "docker",
            "databases",
            "mongodb",
            "typescript",
            "nextjs",
            "prisma",
            "authentication",
            "ci/cd",
            "testing",
            "deployment",
            "graphql",
        ],
        "description": "Own the entire web application stack from UI to database.",
        "tools": ["React", "Node.js", "PostgreSQL", "Docker", "AWS"],
        "certifications": ["AWS Developer Associate", "Meta Full-Stack"],
    },
    {
        "id": 16,
        "title": "Mobile Developer (iOS)",
        "category": "Development",
        "demand": 83,
        "salary_min": 8,
        "salary_max": 22,
        "salary": "₹8-22 LPA",
        "growth": "+14%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "swift",
            "xcode",
            "ios",
            "objective-c",
            "swiftui",
            "core data",
            "networking",
            "git",
            "debugging",
            "uikit",
            "combine",
            "async/await",
            "app store",
            "push notifications",
            "in-app purchases",
            "testing",
        ],
        "description": "Build exceptional native iOS applications for Apple platforms.",
        "tools": ["Xcode", "Swift", "SwiftUI", "Core Data", "TestFlight"],
        "certifications": ["Apple Developer", "Swift Certification"],
    },
    {
        "id": 17,
        "title": "Mobile Developer (Android)",
        "category": "Development",
        "demand": 82,
        "salary_min": 8,
        "salary_max": 21,
        "salary": "₹8-21 LPA",
        "growth": "+13%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "kotlin",
            "java",
            "android",
            "android studio",
            "jetpack compose",
            "room",
            "retrofit",
            "coroutines",
            "git",
            "mvvm",
            "firebase",
            "testing",
            "google play",
            "material design",
            "architecture components",
        ],
        "description": "Develop high-quality Android applications at scale.",
        "tools": ["Android Studio", "Kotlin", "Jetpack Compose", "Firebase", "Gradle"],
        "certifications": ["Google Associate Android Developer"],
    },
    {
        "id": 18,
        "title": "React Native Developer",
        "category": "Development",
        "demand": 81,
        "salary_min": 8,
        "salary_max": 20,
        "salary": "₹8-20 LPA",
        "growth": "+15%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "react native",
            "javascript",
            "typescript",
            "react",
            "redux",
            "expo",
            "ios",
            "android",
            "navigation",
            "git",
            "testing",
            "firebase",
            "push notifications",
            "animations",
            "native modules",
            "fastlane",
        ],
        "description": "Ship cross-platform mobile apps using React Native.",
        "tools": ["Expo", "React Native", "Redux", "Firebase", "Fastlane"],
        "certifications": ["Meta React Native"],
    },
    {
        "id": 19,
        "title": "Blockchain Developer",
        "category": "Development",
        "demand": 82,
        "salary_min": 12,
        "salary_max": 35,
        "salary": "₹12-35 LPA",
        "growth": "+20%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "solidity",
            "ethereum",
            "web3",
            "javascript",
            "smart contracts",
            "cryptography",
            "rust",
            "node.js",
            "defi",
            "nft",
            "distributed systems",
            "hardhat",
            "ipfs",
            "zero knowledge",
            "polygon",
            "layer 2",
            "foundry",
            "account abstraction",
            "dao",
        ],
        "description": "Build decentralized applications and smart contract systems.",
        "tools": ["Hardhat", "Foundry", "ethers.js", "IPFS", "The Graph"],
        "certifications": ["Alchemy University", "Chainlink Developer"],
    },
    {
        "id": 20,
        "title": "Game Developer",
        "category": "Development",
        "demand": 78,
        "salary_min": 7,
        "salary_max": 20,
        "salary": "₹7-20 LPA",
        "growth": "+12%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "unity",
            "c#",
            "unreal engine",
            "c++",
            "game design",
            "graphics",
            "physics simulation",
            "3d modeling",
            "shaders",
            "multiplayer",
            "game ai",
            "audio",
            "optimization",
            "mobile games",
            "vr/ar",
        ],
        "description": "Design and develop immersive gaming experiences.",
        "tools": ["Unity", "Unreal Engine", "Blender", "FMOD", "Photon"],
        "certifications": ["Unity Certified Developer", "Unreal Developer Network"],
    },
    # ─── Infrastructure ───────────────────────────────────────────────────────
    {
        "id": 21,
        "title": "DevOps Engineer",
        "category": "Infrastructure",
        "demand": 90,
        "salary_min": 10,
        "salary_max": 22,
        "salary": "₹10-22 LPA",
        "growth": "+20%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "aws",
            "docker",
            "kubernetes",
            "ci/cd",
            "linux",
            "terraform",
            "ansible",
            "git",
            "jenkins",
            "monitoring",
            "cloud",
            "automation",
            "bash",
            "helm",
            "prometheus",
            "grafana",
            "github actions",
            "argo cd",
            "secrets management",
        ],
        "description": "Accelerate software delivery through automation and culture.",
        "tools": ["Jenkins", "GitLab CI", "ArgoCD", "Prometheus", "Terraform"],
        "certifications": ["CKA", "AWS DevOps Professional", "HashiCorp Terraform"],
    },
    {
        "id": 22,
        "title": "Cloud Architect",
        "category": "Infrastructure",
        "demand": 92,
        "salary_min": 18,
        "salary_max": 40,
        "salary": "₹18-40 LPA",
        "growth": "+22%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "aws",
            "azure",
            "gcp",
            "cloud",
            "kubernetes",
            "terraform",
            "networking",
            "security",
            "docker",
            "automation",
            "cost optimization",
            "microservices",
            "iam",
            "vpc",
            "multi-cloud",
            "disaster recovery",
            "high availability",
            "service mesh",
            "cloud native",
        ],
        "description": "Design fault-tolerant, cost-optimized cloud architectures.",
        "tools": ["AWS", "Azure", "GCP", "Terraform", "Istio"],
        "certifications": [
            "AWS Solutions Architect Professional",
            "Google Cloud Architect",
        ],
    },
    {
        "id": 23,
        "title": "Site Reliability Engineer",
        "category": "Infrastructure",
        "demand": 89,
        "salary_min": 12,
        "salary_max": 25,
        "salary": "₹12-25 LPA",
        "growth": "+22%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "linux",
            "python",
            "monitoring",
            "kubernetes",
            "docker",
            "automation",
            "cloud",
            "networking",
            "bash",
            "prometheus",
            "grafana",
            "incident management",
            "slo",
            "sla",
            "capacity planning",
            "postmortem",
            "chaos engineering",
            "toil reduction",
        ],
        "description": "Keep large-scale distributed systems reliable and performant.",
        "tools": ["Prometheus", "Grafana", "PagerDuty", "Chaos Monkey", "Kubernetes"],
        "certifications": ["CKA", "Google SRE", "AWS SysOps Administrator"],
    },
    {
        "id": 24,
        "title": "Platform Engineer",
        "category": "Infrastructure",
        "demand": 88,
        "salary_min": 14,
        "salary_max": 30,
        "salary": "₹14-30 LPA",
        "growth": "+25%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "kubernetes",
            "platform engineering",
            "terraform",
            "golang",
            "python",
            "ci/cd",
            "developer experience",
            "idp",
            "backstage",
            "crossplane",
            "gitops",
            "service catalog",
            "api gateway",
            "observability",
        ],
        "description": "Build internal developer platforms that accelerate engineering teams.",
        "tools": ["Backstage", "Crossplane", "ArgoCD", "Terraform", "Golang"],
        "certifications": ["CKA", "Platform Engineering Foundation"],
    },
    # ─── Security ─────────────────────────────────────────────────────────────
    {
        "id": 25,
        "title": "Cybersecurity Engineer",
        "category": "Security",
        "demand": 96,
        "salary_min": 12,
        "salary_max": 30,
        "salary": "₹12-30 LPA",
        "growth": "+28%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "security",
            "networking",
            "linux",
            "python",
            "penetration testing",
            "ethical hacking",
            "firewalls",
            "encryption",
            "compliance",
            "siem",
            "vulnerability assessment",
            "zero trust",
            "soc",
            "devsecops",
            "incident response",
            "threat modeling",
            "cryptography",
            "iam",
        ],
        "description": "Defend systems against evolving cyber threats.",
        "tools": ["Burp Suite", "Nmap", "Metasploit", "Splunk", "CrowdStrike"],
        "certifications": ["CISSP", "CEH", "CompTIA Security+", "OSCP"],
    },
    {
        "id": 26,
        "title": "Penetration Tester",
        "category": "Security",
        "demand": 91,
        "salary_min": 10,
        "salary_max": 28,
        "salary": "₹10-28 LPA",
        "growth": "+25%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "penetration testing",
            "ethical hacking",
            "python",
            "linux",
            "networking",
            "web security",
            "exploit development",
            "kali linux",
            "burp suite",
            "metasploit",
            "reverse engineering",
            "malware analysis",
            "social engineering",
            "red teaming",
            "ctf",
            "osint",
        ],
        "description": "Simulate adversarial attacks to find vulnerabilities before attackers do.",
        "tools": ["Kali Linux", "Burp Suite", "Metasploit", "Cobalt Strike", "Shodan"],
        "certifications": ["OSCP", "OSEP", "CEH", "eWPT"],
    },
    {
        "id": 27,
        "title": "Security Architect",
        "category": "Security",
        "demand": 93,
        "salary_min": 18,
        "salary_max": 40,
        "salary": "₹18-40 LPA",
        "growth": "+22%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "security architecture",
            "zero trust",
            "cloud security",
            "iam",
            "encryption",
            "compliance",
            "risk management",
            "devsecops",
            "threat modeling",
            "siem",
            "networking",
            "python",
            "security frameworks",
            "gdpr",
            "iso 27001",
        ],
        "description": "Design enterprise-wide security architecture and governance.",
        "tools": ["AWS Security Hub", "Azure Sentinel", "Prisma Cloud", "Qualys"],
        "certifications": ["CISSP", "CISM", "AWS Security Specialty", "TOGAF"],
    },
    # ─── Management ───────────────────────────────────────────────────────────
    {
        "id": 28,
        "title": "Product Manager (AI)",
        "category": "Management",
        "demand": 88,
        "salary_min": 18,
        "salary_max": 45,
        "salary": "₹18-45 LPA",
        "growth": "+20%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "product management",
            "machine learning",
            "data analysis",
            "agile",
            "roadmapping",
            "stakeholder management",
            "sql",
            "user research",
            "strategy",
            "go-to-market",
            "metrics",
            "okrs",
            "user stories",
            "competitive analysis",
            "a/b testing",
            "product analytics",
        ],
        "description": "Define and deliver AI-powered products from discovery to launch.",
        "tools": ["Jira", "Mixpanel", "Figma", "Amplitude", "Notion"],
        "certifications": ["AIPMM", "Pragmatic Marketing", "Product School"],
    },
    {
        "id": 29,
        "title": "Engineering Manager",
        "category": "Management",
        "demand": 86,
        "salary_min": 25,
        "salary_max": 60,
        "salary": "₹25-60 LPA",
        "growth": "+15%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "leadership",
            "software engineering",
            "agile",
            "team management",
            "hiring",
            "performance reviews",
            "architecture",
            "stakeholder management",
            "mentoring",
            "project management",
            "technical strategy",
            "okrs",
        ],
        "description": "Lead engineering teams to deliver high-impact technical products.",
        "tools": ["Jira", "Confluence", "GitHub", "Notion", "Lattice"],
        "certifications": ["Scrum Master", "PMP", "CTO Academy"],
    },
    {
        "id": 30,
        "title": "Technical Program Manager",
        "category": "Management",
        "demand": 85,
        "salary_min": 18,
        "salary_max": 40,
        "salary": "₹18-40 LPA",
        "growth": "+18%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "program management",
            "agile",
            "scrum",
            "stakeholder management",
            "risk management",
            "software engineering",
            "cross-team coordination",
            "technical writing",
            "roadmapping",
            "metrics",
            "jira",
            "confluence",
        ],
        "description": "Orchestrate large-scale technical programs across multiple teams.",
        "tools": ["Jira", "Confluence", "Asana", "MS Project", "Smartsheet"],
        "certifications": ["PMP", "PMI-ACP", "Google PM Certificate"],
    },
    # ─── Finance ──────────────────────────────────────────────────────────────
    {
        "id": 31,
        "title": "Quantitative Analyst",
        "category": "Finance",
        "demand": 90,
        "salary_min": 15,
        "salary_max": 40,
        "salary": "₹15-40 LPA",
        "growth": "+18%",
        "remote": False,
        "difficulty": "Expert",
        "tags": [
            "python",
            "mathematics",
            "statistics",
            "machine learning",
            "r",
            "sql",
            "financial modeling",
            "risk analysis",
            "matlab",
            "deep learning",
            "time series",
            "stochastic calculus",
            "options pricing",
            "monte carlo",
            "portfolio optimization",
            "factor models",
        ],
        "description": "Apply mathematical models to financial markets and risk.",
        "tools": ["Python", "R", "MATLAB", "Bloomberg", "QuantLib"],
        "certifications": ["CFA", "FRM", "CQF"],
    },
    {
        "id": 32,
        "title": "Algorithmic Trader",
        "category": "Finance",
        "demand": 87,
        "salary_min": 18,
        "salary_max": 60,
        "salary": "₹18-60 LPA",
        "growth": "+15%",
        "remote": False,
        "difficulty": "Expert",
        "tags": [
            "python",
            "c++",
            "machine learning",
            "time series",
            "statistics",
            "sql",
            "financial markets",
            "backtesting",
            "risk management",
            "market microstructure",
            "high frequency trading",
            "execution algorithms",
            "low latency",
        ],
        "description": "Design and execute systematic trading strategies.",
        "tools": ["Python", "C++", "QuantConnect", "Backtrader", "Interactive Brokers"],
        "certifications": ["CFA Level 1", "FRM", "CQF"],
    },
    {
        "id": 33,
        "title": "FinTech Engineer",
        "category": "Finance",
        "demand": 88,
        "salary_min": 12,
        "salary_max": 30,
        "salary": "₹12-30 LPA",
        "growth": "+22%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "node.js",
            "java",
            "payment systems",
            "banking apis",
            "security",
            "rest api",
            "sql",
            "cloud",
            "compliance",
            "pci-dss",
            "fraud detection",
            "microservices",
            "kafka",
            "real-time processing",
        ],
        "description": "Build secure, compliant financial technology products.",
        "tools": ["Stripe", "Plaid", "Kafka", "PostgreSQL", "AWS"],
        "certifications": ["AWS Financial Services", "PCI DSS"],
    },
    # ─── Engineering ──────────────────────────────────────────────────────────
    {
        "id": 34,
        "title": "Robotics Engineer",
        "category": "Engineering",
        "demand": 86,
        "salary_min": 10,
        "salary_max": 25,
        "salary": "₹10-25 LPA",
        "growth": "+22%",
        "remote": False,
        "difficulty": "Hard",
        "tags": [
            "python",
            "ros",
            "c++",
            "computer vision",
            "machine learning",
            "embedded systems",
            "sensors",
            "automation",
            "control systems",
            "mathematics",
            "slam",
            "motion planning",
            "actuators",
            "simulation",
            "mechatronics",
            "lidar",
            "ros2",
        ],
        "description": "Design intelligent robotic systems for automation and autonomy.",
        "tools": ["ROS2", "Gazebo", "OpenCV", "MoveIt", "MATLAB"],
        "certifications": ["ROS Developer", "Robotics Specialization Coursera"],
    },
    {
        "id": 35,
        "title": "Embedded Systems Engineer",
        "category": "Engineering",
        "demand": 84,
        "salary_min": 8,
        "salary_max": 22,
        "salary": "₹8-22 LPA",
        "growth": "+15%",
        "remote": False,
        "difficulty": "Hard",
        "tags": [
            "c",
            "c++",
            "embedded systems",
            "rtos",
            "microcontrollers",
            "fpga",
            "hardware",
            "debugging",
            "iot",
            "protocols",
            "arm",
            "linux kernel",
            "device drivers",
            "bare metal",
            "power management",
            "dsp",
        ],
        "description": "Program microcontrollers and embedded Linux systems.",
        "tools": ["GCC", "JTAG", "Oscilloscope", "FreeRTOS", "Yocto"],
        "certifications": [
            "ARM Accredited Engineer",
            "Embedded Systems Specialization",
        ],
    },
    {
        "id": 36,
        "title": "IoT Engineer",
        "category": "Engineering",
        "demand": 85,
        "salary_min": 8,
        "salary_max": 20,
        "salary": "₹8-20 LPA",
        "growth": "+25%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "iot",
            "python",
            "c",
            "mqtt",
            "aws iot",
            "embedded systems",
            "sensors",
            "networking",
            "cloud",
            "edge computing",
            "security",
            "protocols",
            "raspberry pi",
            "arduino",
            "data streams",
            "real-time analytics",
        ],
        "description": "Connect and manage intelligent IoT device ecosystems.",
        "tools": ["AWS IoT", "MQTT", "Raspberry Pi", "Arduino", "InfluxDB"],
        "certifications": ["AWS IoT Specialty", "CompTIA IoT+"],
    },
    {
        "id": 37,
        "title": "AR/VR Developer",
        "category": "Engineering",
        "demand": 82,
        "salary_min": 10,
        "salary_max": 28,
        "salary": "₹10-28 LPA",
        "growth": "+30%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "unity",
            "unreal engine",
            "c#",
            "c++",
            "3d modeling",
            "spatial computing",
            "openxr",
            "arcore",
            "arkit",
            "shaders",
            "real-time rendering",
            "computer vision",
            "hand tracking",
            "haptics",
            "performance optimization",
        ],
        "description": "Create immersive spatial computing experiences.",
        "tools": ["Unity", "Unreal Engine", "Vuforia", "Blender", "Meta Quest SDK"],
        "certifications": ["Unity Certified Expert", "Meta Spark Creator"],
    },
    # ─── Design ───────────────────────────────────────────────────────────────
    {
        "id": 38,
        "title": "UX/UI Designer",
        "category": "Design",
        "demand": 80,
        "salary_min": 6,
        "salary_max": 18,
        "salary": "₹6-18 LPA",
        "growth": "+15%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "figma",
            "ui/ux",
            "user research",
            "prototyping",
            "wireframing",
            "design systems",
            "usability testing",
            "accessibility",
            "sketch",
            "adobe xd",
            "information architecture",
            "interaction design",
            "typography",
            "color theory",
            "css",
            "design thinking",
        ],
        "description": "Design intuitive digital products centered on user needs.",
        "tools": ["Figma", "FigJam", "Maze", "Hotjar", "Zeplin"],
        "certifications": ["Google UX Design Certificate", "Nielsen Norman Group"],
    },
    {
        "id": 39,
        "title": "Design Engineer",
        "category": "Design",
        "demand": 82,
        "salary_min": 8,
        "salary_max": 20,
        "salary": "₹8-20 LPA",
        "growth": "+20%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "figma",
            "react",
            "css",
            "typescript",
            "design systems",
            "animation",
            "accessibility",
            "storybook",
            "component libraries",
            "prototyping",
            "web standards",
            "performance",
            "svg",
            "motion design",
        ],
        "description": "Bridge the gap between design vision and code implementation.",
        "tools": ["Figma", "Storybook", "React", "Framer Motion", "Chromatic"],
        "certifications": ["Google UX Design", "Meta Front-End Developer"],
    },
    # ─── Research & Science ───────────────────────────────────────────────────
    {
        "id": 40,
        "title": "Bioinformatics Scientist",
        "category": "Research",
        "demand": 84,
        "salary_min": 10,
        "salary_max": 28,
        "salary": "₹10-28 LPA",
        "growth": "+20%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "python",
            "r",
            "machine learning",
            "statistics",
            "genomics",
            "bioinformatics",
            "sql",
            "bash",
            "deep learning",
            "data analysis",
            "biological databases",
            "sequence analysis",
            "protein structure",
            "single cell",
            "multi-omics",
        ],
        "description": "Apply computational methods to biological data discovery.",
        "tools": ["BioPython", "R/Bioconductor", "Galaxy", "Nextflow", "GATK"],
        "certifications": ["Bioinformatics Specialization Coursera"],
    },
    {
        "id": 41,
        "title": "Computational Neuroscientist",
        "category": "Research",
        "demand": 80,
        "salary_min": 12,
        "salary_max": 30,
        "salary": "₹12-30 LPA",
        "growth": "+18%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "python",
            "matlab",
            "neuroscience",
            "machine learning",
            "statistics",
            "signal processing",
            "deep learning",
            "data analysis",
            "imaging",
            "brain-computer interface",
            "eeg",
            "fmri",
            "computational modeling",
        ],
        "description": "Model brain function using computational and AI techniques.",
        "tools": ["MATLAB", "Python", "MNE", "FreeSurfer", "SPM"],
        "certifications": ["Neuromatch Academy"],
    },
    {
        "id": 42,
        "title": "Climate Data Scientist",
        "category": "Research",
        "demand": 83,
        "salary_min": 10,
        "salary_max": 25,
        "salary": "₹10-25 LPA",
        "growth": "+22%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "machine learning",
            "statistics",
            "geospatial",
            "climate modeling",
            "data analysis",
            "netcdf",
            "xarray",
            "satellite data",
            "visualization",
            "sql",
            "cloud",
            "deep learning",
            "time series",
            "r",
        ],
        "description": "Apply data science to understand and predict climate systems.",
        "tools": ["Xarray", "Dask", "GDAL", "Pangeo", "Google Earth Engine"],
        "certifications": ["Climate Change AI Summer School"],
    },
    # ─── Cloud & SaaS ─────────────────────────────────────────────────────────
    {
        "id": 43,
        "title": "Salesforce Developer",
        "category": "Cloud & SaaS",
        "demand": 85,
        "salary_min": 8,
        "salary_max": 22,
        "salary": "₹8-22 LPA",
        "growth": "+15%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "salesforce",
            "apex",
            "lwc",
            "soql",
            "crm",
            "javascript",
            "rest api",
            "integration",
            "automation",
            "flows",
            "administration",
            "data modeling",
        ],
        "description": "Customize and extend the Salesforce platform for enterprise clients.",
        "tools": ["Salesforce", "VS Code", "SOQL", "MuleSoft", "Workbench"],
        "certifications": ["Salesforce Certified Developer", "Platform App Builder"],
    },
    {
        "id": 44,
        "title": "AWS Solutions Architect",
        "category": "Cloud & SaaS",
        "demand": 91,
        "salary_min": 15,
        "salary_max": 35,
        "salary": "₹15-35 LPA",
        "growth": "+20%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "aws",
            "cloud",
            "architecture",
            "terraform",
            "networking",
            "security",
            "serverless",
            "lambda",
            "s3",
            "ec2",
            "rds",
            "iam",
            "cost optimization",
            "high availability",
            "microservices",
            "cloudformation",
        ],
        "description": "Design and implement scalable AWS cloud solutions.",
        "tools": ["AWS Console", "Terraform", "CloudFormation", "AWS CDK"],
        "certifications": [
            "AWS Solutions Architect Professional",
            "AWS DevOps Professional",
        ],
    },
    {
        "id": 45,
        "title": "GCP Data Engineer",
        "category": "Cloud & SaaS",
        "demand": 88,
        "salary_min": 14,
        "salary_max": 32,
        "salary": "₹14-32 LPA",
        "growth": "+22%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "gcp",
            "bigquery",
            "dataflow",
            "python",
            "sql",
            "pubsub",
            "cloud storage",
            "dataproc",
            "looker",
            "terraform",
            "spark",
            "data pipelines",
            "cloud functions",
            "composer",
            "dbt",
        ],
        "description": "Build data infrastructure on the Google Cloud Platform.",
        "tools": ["BigQuery", "Dataflow", "Dataproc", "Cloud Composer", "Looker"],
        "certifications": [
            "Google Professional Data Engineer",
            "Associate Cloud Engineer",
        ],
    },
    # ─── QA & Testing ─────────────────────────────────────────────────────────
    {
        "id": 46,
        "title": "QA Automation Engineer",
        "category": "QA & Testing",
        "demand": 82,
        "salary_min": 7,
        "salary_max": 18,
        "salary": "₹7-18 LPA",
        "growth": "+15%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "selenium",
            "python",
            "java",
            "testing",
            "automation",
            "pytest",
            "junit",
            "rest api",
            "git",
            "ci/cd",
            "performance testing",
            "cypress",
            "playwright",
            "test planning",
            "bdd",
            "appium",
        ],
        "description": "Build automated testing frameworks to ensure software quality.",
        "tools": ["Selenium", "Cypress", "Playwright", "JMeter", "TestNG"],
        "certifications": ["ISTQB", "Selenium Certification"],
    },
    {
        "id": 47,
        "title": "Performance Engineer",
        "category": "QA & Testing",
        "demand": 80,
        "salary_min": 8,
        "salary_max": 20,
        "salary": "₹8-20 LPA",
        "growth": "+12%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "performance testing",
            "jmeter",
            "gatling",
            "python",
            "load testing",
            "monitoring",
            "profiling",
            "apm",
            "java",
            "distributed systems",
            "database optimization",
            "caching",
            "benchmarking",
            "k6",
        ],
        "description": "Ensure applications perform under load and scale gracefully.",
        "tools": ["JMeter", "Gatling", "k6", "Dynatrace", "New Relic"],
        "certifications": ["ISTQB Performance Testing"],
    },
    # ─── Healthcare & EdTech ─────────────────────────────────────────────────
    {
        "id": 48,
        "title": "Health Informatics Engineer",
        "category": "HealthTech",
        "demand": 85,
        "salary_min": 10,
        "salary_max": 25,
        "salary": "₹10-25 LPA",
        "growth": "+25%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "sql",
            "machine learning",
            "hl7",
            "fhir",
            "healthcare data",
            "ehr",
            "data analysis",
            "statistics",
            "privacy",
            "hipaa",
            "nlp",
            "clinical data",
            "medical imaging",
            "icd coding",
        ],
        "description": "Apply data engineering and AI to transform healthcare delivery.",
        "tools": ["Epic", "FHIR", "Python", "SQL", "Tableau"],
        "certifications": ["RHIA", "HL7 FHIR Fundamentals"],
    },
    {
        "id": 49,
        "title": "EdTech Engineer",
        "category": "HealthTech",
        "demand": 78,
        "salary_min": 7,
        "salary_max": 18,
        "salary": "₹7-18 LPA",
        "growth": "+20%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "python",
            "react",
            "node.js",
            "sql",
            "lms",
            "adaptive learning",
            "machine learning",
            "recommendation systems",
            "gamification",
            "video streaming",
            "mobile",
            "accessibility",
            "data analysis",
        ],
        "description": "Build adaptive learning platforms powered by AI.",
        "tools": ["Canvas", "Moodle", "React", "Node.js", "AWS"],
        "certifications": ["Google Educator", "Instructional Design"],
    },
    # ─── Additional Specialized Roles ────────────────────────────────────────
    {
        "id": 50,
        "title": "Data Privacy Engineer",
        "category": "Security",
        "demand": 87,
        "salary_min": 12,
        "salary_max": 28,
        "salary": "₹12-28 LPA",
        "growth": "+30%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "privacy",
            "gdpr",
            "ccpa",
            "data governance",
            "anonymization",
            "encryption",
            "compliance",
            "sql",
            "risk assessment",
            "pii",
            "differential privacy",
            "federated learning",
            "audit",
        ],
        "description": "Engineer privacy-by-design into data systems and products.",
        "tools": ["OneTrust", "BigID", "Privitar", "AWS Macie", "Collibra"],
        "certifications": ["CIPP/E", "CIPM", "CDPSE"],
    },
    {
        "id": 51,
        "title": "Search Engineer",
        "category": "Development",
        "demand": 85,
        "salary_min": 12,
        "salary_max": 28,
        "salary": "₹12-28 LPA",
        "growth": "+18%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "elasticsearch",
            "python",
            "nlp",
            "java",
            "information retrieval",
            "search ranking",
            "vector search",
            "lucene",
            "solr",
            "machine learning",
            "recommendation systems",
            "query understanding",
            "relevance engineering",
        ],
        "description": "Build and optimize search and discovery systems at scale.",
        "tools": ["Elasticsearch", "Solr", "Weaviate", "Pinecone", "Vespa"],
        "certifications": ["Elastic Engineer", "OpenSearch Certified"],
    },
    {
        "id": 52,
        "title": "Streaming Systems Engineer",
        "category": "Data",
        "demand": 87,
        "salary_min": 14,
        "salary_max": 30,
        "salary": "₹14-30 LPA",
        "growth": "+25%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "kafka",
            "flink",
            "spark streaming",
            "java",
            "python",
            "scala",
            "real-time processing",
            "distributed systems",
            "cloud",
            "sql",
            "data pipelines",
            "event-driven architecture",
            "confluent",
        ],
        "description": "Build real-time data streaming infrastructure.",
        "tools": ["Apache Kafka", "Apache Flink", "Confluent", "Spark", "Kinesis"],
        "certifications": ["Confluent Certified Developer", "Databricks Certified"],
    },
    {
        "id": 53,
        "title": "Graph Database Engineer",
        "category": "Data",
        "demand": 80,
        "salary_min": 12,
        "salary_max": 26,
        "salary": "₹12-26 LPA",
        "growth": "+20%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "graph databases",
            "neo4j",
            "cypher",
            "python",
            "knowledge graphs",
            "gremlin",
            "sparql",
            "rdf",
            "graph algorithms",
            "machine learning",
            "recommender systems",
            "fraud detection",
            "network analysis",
        ],
        "description": "Design and query graph-based data systems.",
        "tools": ["Neo4j", "Amazon Neptune", "TigerGraph", "GraphQL", "ArangoDB"],
        "certifications": ["Neo4j Certified Professional"],
    },
    {
        "id": 54,
        "title": "API Platform Engineer",
        "category": "Development",
        "demand": 86,
        "salary_min": 10,
        "salary_max": 24,
        "salary": "₹10-24 LPA",
        "growth": "+18%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "rest api",
            "graphql",
            "grpc",
            "node.js",
            "python",
            "api design",
            "authentication",
            "rate limiting",
            "api gateway",
            "swagger",
            "microservices",
            "developer experience",
            "sdk development",
            "webhooks",
        ],
        "description": "Build and govern APIs that power third-party integrations.",
        "tools": ["Kong", "Apigee", "Postman", "Swagger", "AWS API Gateway"],
        "certifications": ["API Security Architect", "Kong Certified"],
    },
    {
        "id": 55,
        "title": "Observability Engineer",
        "category": "Infrastructure",
        "demand": 86,
        "salary_min": 12,
        "salary_max": 26,
        "salary": "₹12-26 LPA",
        "growth": "+22%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "prometheus",
            "grafana",
            "opentelemetry",
            "tracing",
            "logging",
            "metrics",
            "python",
            "kubernetes",
            "distributed systems",
            "alerting",
            "apm",
            "datadog",
            "new relic",
            "elk stack",
        ],
        "description": "Give engineering teams deep visibility into distributed systems.",
        "tools": ["Prometheus", "Grafana", "Datadog", "Jaeger", "OpenTelemetry"],
        "certifications": ["Datadog Fundamentals", "OpenTelemetry Certification"],
    },
    {
        "id": 56,
        "title": "Database Reliability Engineer",
        "category": "Infrastructure",
        "demand": 84,
        "salary_min": 12,
        "salary_max": 28,
        "salary": "₹12-28 LPA",
        "growth": "+18%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "postgresql",
            "mysql",
            "sql",
            "database administration",
            "performance tuning",
            "backup",
            "replication",
            "cloud",
            "python",
            "bash",
            "monitoring",
            "query optimization",
            "high availability",
            "disaster recovery",
            "nosql",
        ],
        "description": "Ensure databases are reliable, performant, and scalable.",
        "tools": ["PostgreSQL", "MySQL", "Patroni", "pgBouncer", "Percona"],
        "certifications": ["Oracle DBA", "PostgreSQL Certified"],
    },
    {
        "id": 57,
        "title": "SupplyChain Tech Lead",
        "category": "Management",
        "demand": 81,
        "salary_min": 14,
        "salary_max": 32,
        "salary": "₹14-32 LPA",
        "growth": "+15%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "machine learning",
            "optimization",
            "operations research",
            "sql",
            "forecasting",
            "logistics",
            "erp",
            "sap",
            "data analysis",
            "simulation",
            "network optimization",
            "inventory management",
        ],
        "description": "Apply algorithmic optimization to supply chain challenges.",
        "tools": ["SAP", "Python", "Gurobi", "CPLEX", "Tableau"],
        "certifications": ["APICS CSCP", "Supply Chain Management"],
    },
    {
        "id": 58,
        "title": "Legal Tech Engineer",
        "category": "Development",
        "demand": 79,
        "salary_min": 10,
        "salary_max": 24,
        "salary": "₹10-24 LPA",
        "growth": "+20%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "nlp",
            "machine learning",
            "contract analysis",
            "legal ai",
            "document processing",
            "ocr",
            "rest api",
            "sql",
            "compliance",
            "llm",
        ],
        "description": "Automate legal workflows with AI and natural language processing.",
        "tools": ["Python", "LangChain", "OpenAI", "Elasticsearch", "AWS Textract"],
        "certifications": ["Legal Technology Foundation"],
    },
    {
        "id": 59,
        "title": "Autonomous Systems Engineer",
        "category": "Engineering",
        "demand": 89,
        "salary_min": 16,
        "salary_max": 40,
        "salary": "₹16-40 LPA",
        "growth": "+35%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "c++",
            "python",
            "ros",
            "computer vision",
            "machine learning",
            "lidar",
            "slam",
            "sensor fusion",
            "path planning",
            "deep learning",
            "kalman filter",
            "simulation",
            "real-time systems",
            "embedded systems",
            "control systems",
        ],
        "description": "Build the AI stack for autonomous vehicles and drones.",
        "tools": ["ROS2", "CARLA", "Gazebo", "CUDA", "MATLAB"],
        "certifications": ["Autonomous Systems Nanodegree", "Udacity Self-Driving Car"],
    },
    {
        "id": 60,
        "title": "Prompt Engineer",
        "category": "AI/ML",
        "demand": 92,
        "salary_min": 10,
        "salary_max": 28,
        "salary": "₹10-28 LPA",
        "growth": "+80%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "prompt engineering",
            "llm",
            "python",
            "langchain",
            "nlp",
            "openai",
            "anthropic",
            "evaluation",
            "rag",
            "few-shot learning",
            "chain of thought",
            "agent design",
            "tool use",
            "context management",
            "fine-tuning",
        ],
        "description": "Maximize LLM performance through expert prompt design and evaluation.",
        "tools": ["OpenAI", "Anthropic", "LangChain", "PromptFlow", "Weights & Biases"],
        "certifications": ["DeepLearning.AI Prompt Engineering", "OpenAI Developer"],
    },
    {
        "id": 61,
        "title": "Digital Twin Engineer",
        "category": "Engineering",
        "demand": 82,
        "salary_min": 12,
        "salary_max": 28,
        "salary": "₹12-28 LPA",
        "growth": "+30%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "iot",
            "simulation",
            "python",
            "cloud",
            "digital twin",
            "3d modeling",
            "data pipelines",
            "real-time analytics",
            "machine learning",
            "aws",
            "azure",
            "unity",
            "apis",
            "physics simulation",
        ],
        "description": "Create virtual replicas of physical systems for monitoring and optimization.",
        "tools": ["Azure Digital Twins", "AWS IoT TwinMaker", "Unity", "MATLAB"],
        "certifications": ["Digital Twin Foundation", "Siemens MindSphere"],
    },
    {
        "id": 62,
        "title": "Conversational AI Engineer",
        "category": "AI/ML",
        "demand": 90,
        "salary_min": 12,
        "salary_max": 30,
        "salary": "₹12-30 LPA",
        "growth": "+45%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "nlp",
            "llm",
            "dialogflow",
            "rasa",
            "intent classification",
            "entity extraction",
            "langchain",
            "voice interfaces",
            "speech recognition",
            "tts",
            "bot development",
            "api integration",
            "rag",
            "evaluation",
        ],
        "description": "Build intelligent voice and chat assistants.",
        "tools": ["Rasa", "Dialogflow", "LangChain", "Whisper", "ElevenLabs"],
        "certifications": ["Google Cloud Dialogflow", "Rasa Certified Developer"],
    },
    {
        "id": 63,
        "title": "MLSecOps Engineer",
        "category": "Security",
        "demand": 88,
        "salary_min": 15,
        "salary_max": 35,
        "salary": "₹15-35 LPA",
        "growth": "+40%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "machine learning",
            "security",
            "adversarial attacks",
            "model robustness",
            "data poisoning",
            "python",
            "mlops",
            "devsecops",
            "privacy",
            "compliance",
            "model explainability",
            "fairness",
            "risk assessment",
            "threat modeling",
        ],
        "description": "Secure ML systems against adversarial threats and data vulnerabilities.",
        "tools": ["Adversarial Robustness Toolbox", "Counterfit", "Alibi Detect"],
        "certifications": ["CISSP", "AWS ML Specialty", "Responsible AI Certification"],
    },
    {
        "id": 64,
        "title": "Spatial Computing Engineer",
        "category": "Engineering",
        "demand": 84,
        "salary_min": 14,
        "salary_max": 32,
        "salary": "₹14-32 LPA",
        "growth": "+40%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "arkit",
            "arcore",
            "unity",
            "unreal engine",
            "spatial audio",
            "hand tracking",
            "scene understanding",
            "lidar",
            "computer vision",
            "c#",
            "swift",
            "kotlin",
            "3d rendering",
            "physics",
            "optimization",
            "visionos",
        ],
        "description": "Build next-generation spatial computing applications.",
        "tools": ["Apple Vision Pro SDK", "Meta Quest SDK", "ARKit", "Unity", "Unreal"],
        "certifications": ["Apple Developer", "Meta Spark Creator"],
    },
    {
        "id": 65,
        "title": "Synthetic Data Engineer",
        "category": "AI/ML",
        "demand": 83,
        "salary_min": 12,
        "salary_max": 28,
        "salary": "₹12-28 LPA",
        "growth": "+35%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "generative models",
            "gan",
            "diffusion models",
            "simulation",
            "data augmentation",
            "privacy",
            "machine learning",
            "statistics",
            "computer vision",
            "nlp",
            "evaluation",
            "dataset curation",
        ],
        "description": "Generate high-quality synthetic training data for AI systems.",
        "tools": ["Gretel.ai", "Mostly AI", "CTGAN", "SDV", "Faker"],
        "certifications": ["Synthetic Data Specialization"],
    },
    {
        "id": 66,
        "title": "AI Ethics & Governance Lead",
        "category": "Research",
        "demand": 85,
        "salary_min": 14,
        "salary_max": 35,
        "salary": "₹14-35 LPA",
        "growth": "+45%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "ai ethics",
            "machine learning",
            "policy",
            "fairness",
            "explainability",
            "risk assessment",
            "governance",
            "compliance",
            "statistics",
            "research",
            "stakeholder management",
            "responsible ai",
            "audit",
            "documentation",
        ],
        "description": "Ensure AI systems are fair, transparent, and accountable.",
        "tools": ["IBM AI Fairness 360", "LIME", "SHAP", "Responsible AI Dashboard"],
        "certifications": ["IEEE AI Ethics Certification", "Responsible AI Institute"],
    },
    {
        "id": 67,
        "title": "Infrastructure Cost Engineer",
        "category": "Infrastructure",
        "demand": 82,
        "salary_min": 12,
        "salary_max": 28,
        "salary": "₹12-28 LPA",
        "growth": "+20%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "aws",
            "azure",
            "gcp",
            "cloud",
            "cost optimization",
            "terraform",
            "finops",
            "python",
            "monitoring",
            "kubernetes",
            "reserved instances",
            "tagging",
            "budget alerts",
            "rightsizing",
            "spot instances",
        ],
        "description": "Optimize cloud infrastructure costs without sacrificing performance.",
        "tools": ["AWS Cost Explorer", "Infracost", "Spot.io", "CloudHealth", "Apptio"],
        "certifications": ["FinOps Certified Practitioner", "AWS Cost Optimization"],
    },
    {
        "id": 68,
        "title": "Open Source Developer",
        "category": "Development",
        "demand": 80,
        "salary_min": 8,
        "salary_max": 22,
        "salary": "₹8-22 LPA",
        "growth": "+12%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "javascript",
            "git",
            "open source",
            "community",
            "documentation",
            "ci/cd",
            "testing",
            "code review",
            "apis",
            "linux",
            "contributing",
            "github",
            "versioning",
            "release management",
        ],
        "description": "Contribute to and maintain open source software ecosystems.",
        "tools": ["GitHub", "GitLab", "CI Actions", "Sphinx", "ReadTheDocs"],
        "certifications": ["Linux Foundation Certified Developer"],
    },
    {
        "id": 69,
        "title": "Data Governance Engineer",
        "category": "Data",
        "demand": 83,
        "salary_min": 12,
        "salary_max": 28,
        "salary": "₹12-28 LPA",
        "growth": "+25%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "data governance",
            "data catalog",
            "sql",
            "python",
            "data quality",
            "metadata management",
            "compliance",
            "data lineage",
            "privacy",
            "policies",
            "documentation",
            "dbt",
            "great expectations",
            "collibra",
        ],
        "description": "Establish data quality, cataloging, and governance frameworks.",
        "tools": ["Collibra", "Apache Atlas", "Great Expectations", "dbt", "Amundsen"],
        "certifications": ["CDMP", "Data Governance and Stewardship Professional"],
    },
    {
        "id": 70,
        "title": "Technical Writer (AI/ML)",
        "category": "Management",
        "demand": 76,
        "salary_min": 6,
        "salary_max": 18,
        "salary": "₹6-18 LPA",
        "growth": "+15%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "technical writing",
            "documentation",
            "python",
            "machine learning",
            "api documentation",
            "markdown",
            "git",
            "developer experience",
            "communication",
            "tutorials",
            "sdks",
            "openapi",
            "diataxis",
        ],
        "description": "Create crystal-clear documentation for AI and developer tools.",
        "tools": ["Sphinx", "MkDocs", "Notion", "Confluence", "Readme.io"],
        "certifications": ["Google Technical Writing", "API Documentation"],
    },
    # Roles 71-80
    {
        "id": 71,
        "title": "MLflow & Experiment Tracking Engineer",
        "category": "AI/ML",
        "demand": 86,
        "salary_min": 13,
        "salary_max": 30,
        "salary": "₹13-30 LPA",
        "growth": "+30%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "mlflow",
            "python",
            "experiment tracking",
            "model registry",
            "hyperparameter tuning",
            "optuna",
            "wandb",
            "machine learning",
            "docker",
            "kubernetes",
            "feature store",
        ],
        "description": "Manage ML experiments, models, and reproducibility at scale.",
        "tools": ["MLflow", "Weights & Biases", "Optuna", "DVC", "Hydra"],
        "certifications": ["Databricks MLflow", "Weights & Biases Certified"],
    },
    {
        "id": 72,
        "title": "Time Series Analyst",
        "category": "Data",
        "demand": 82,
        "salary_min": 10,
        "salary_max": 24,
        "salary": "₹10-24 LPA",
        "growth": "+18%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "python",
            "time series",
            "forecasting",
            "statistics",
            "machine learning",
            "arima",
            "prophet",
            "lstm",
            "anomaly detection",
            "r",
            "sql",
            "signal processing",
            "energy",
            "finance",
            "monitoring",
        ],
        "description": "Forecast and model sequential temporal data.",
        "tools": ["Prophet", "statsmodels", "Darts", "Nixtla", "Grafana"],
        "certifications": ["Time Series Specialization Coursera"],
    },
    {
        "id": 73,
        "title": "Knowledge Graph Engineer",
        "category": "AI/ML",
        "demand": 81,
        "salary_min": 12,
        "salary_max": 28,
        "salary": "₹12-28 LPA",
        "growth": "+22%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "knowledge graphs",
            "rdf",
            "owl",
            "sparql",
            "python",
            "nlp",
            "entity resolution",
            "ontology",
            "neo4j",
            "llm",
            "information extraction",
            "wikidata",
            "reasoning",
        ],
        "description": "Build knowledge graphs that give AI systems world understanding.",
        "tools": ["Neo4j", "Apache Jena", "Stardog", "OpenLink Virtuoso", "Wikidata"],
        "certifications": [
            "Neo4j Certified Professional",
            "Knowledge Graph Specialization",
        ],
    },
    {
        "id": 74,
        "title": "Causal AI Engineer",
        "category": "AI/ML",
        "demand": 85,
        "salary_min": 15,
        "salary_max": 35,
        "salary": "₹15-35 LPA",
        "growth": "+35%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "causal inference",
            "python",
            "machine learning",
            "statistics",
            "econometrics",
            "a/b testing",
            "bayesian statistics",
            "counterfactuals",
            "dag",
            "dowhy",
            "econml",
            "experimentation",
            "policy evaluation",
        ],
        "description": "Apply causal reasoning to make AI decisions trustworthy.",
        "tools": ["DoWhy", "EconML", "CausalPy", "Pyro", "Stan"],
        "certifications": ["Causal Inference Specialization"],
    },
    {
        "id": 75,
        "title": "Federated Learning Engineer",
        "category": "AI/ML",
        "demand": 83,
        "salary_min": 14,
        "salary_max": 32,
        "salary": "₹14-32 LPA",
        "growth": "+38%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "federated learning",
            "python",
            "machine learning",
            "privacy",
            "differential privacy",
            "distributed systems",
            "tensorflow",
            "pytorch",
            "flower",
            "pysyft",
            "secure aggregation",
            "edge ai",
        ],
        "description": "Train models across distributed private data without centralization.",
        "tools": ["Flower", "PySyft", "TensorFlow Federated", "OpenFL", "FATE"],
        "certifications": [
            "Privacy Engineering Certification",
            "Federated Learning Specialization",
        ],
    },
    {
        "id": 76,
        "title": "Quantum Computing Developer",
        "category": "Research",
        "demand": 80,
        "salary_min": 16,
        "salary_max": 45,
        "salary": "₹16-45 LPA",
        "growth": "+40%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "quantum computing",
            "python",
            "qiskit",
            "cirq",
            "mathematics",
            "linear algebra",
            "quantum algorithms",
            "optimization",
            "cryptography",
            "machine learning",
            "physics",
            "quantum error correction",
        ],
        "description": "Program quantum computers for optimization and simulation.",
        "tools": ["Qiskit", "Cirq", "PennyLane", "AWS Braket", "IBM Quantum"],
        "certifications": ["IBM Quantum Computing", "Qiskit Advocate"],
    },
    {
        "id": 77,
        "title": "Edge AI Engineer",
        "category": "AI/ML",
        "demand": 88,
        "salary_min": 12,
        "salary_max": 30,
        "salary": "₹12-30 LPA",
        "growth": "+40%",
        "remote": True,
        "difficulty": "Hard",
        "tags": [
            "edge computing",
            "tensorflow lite",
            "tflite",
            "onnx",
            "model quantization",
            "model pruning",
            "embedded systems",
            "python",
            "c++",
            "iot",
            "nvidia jetson",
            "raspberry pi",
            "real-time inference",
            "mobile deployment",
        ],
        "description": "Deploy AI models on edge devices with tight resource constraints.",
        "tools": [
            "TensorFlow Lite",
            "ONNX",
            "OpenVINO",
            "NVIDIA TensorRT",
            "MediaPipe",
        ],
        "certifications": ["NVIDIA Deep Learning Institute", "Edge AI Specialization"],
    },
    {
        "id": 78,
        "title": "AI Product Analyst",
        "category": "Management",
        "demand": 84,
        "salary_min": 10,
        "salary_max": 25,
        "salary": "₹10-25 LPA",
        "growth": "+20%",
        "remote": True,
        "difficulty": "Medium",
        "tags": [
            "product analytics",
            "python",
            "sql",
            "a/b testing",
            "machine learning",
            "data visualization",
            "statistics",
            "business intelligence",
            "metrics",
            "user research",
            "experimentation",
            "tableau",
            "mixpanel",
            "looker",
        ],
        "description": "Analyze AI product performance and surface actionable insights.",
        "tools": ["Mixpanel", "Amplitude", "Looker", "SQL", "Python"],
        "certifications": ["Product Analytics Certification", "Google Analytics"],
    },
    {
        "id": 79,
        "title": "MLOps Platform Lead",
        "category": "AI/ML",
        "demand": 90,
        "salary_min": 20,
        "salary_max": 50,
        "salary": "₹20-50 LPA",
        "growth": "+35%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "mlops",
            "platform engineering",
            "kubernetes",
            "terraform",
            "python",
            "model serving",
            "feature store",
            "data versioning",
            "ci/cd",
            "monitoring",
            "leadership",
            "architecture",
            "cloud",
            "cost optimization",
            "sre",
        ],
        "description": "Lead the team building enterprise ML platform infrastructure.",
        "tools": ["Kubeflow", "Vertex AI", "SageMaker", "Feast", "Argo Workflows"],
        "certifications": [
            "CKA",
            "Google Professional ML Engineer",
            "AWS ML Specialty",
        ],
    },
    {
        "id": 80,
        "title": "AI Infrastructure Engineer",
        "category": "Infrastructure",
        "demand": 91,
        "salary_min": 18,
        "salary_max": 45,
        "salary": "₹18-45 LPA",
        "growth": "+42%",
        "remote": True,
        "difficulty": "Expert",
        "tags": [
            "gpu infrastructure",
            "cuda",
            "python",
            "kubernetes",
            "distributed training",
            "networking",
            "storage",
            "cloud",
            "cost optimization",
            "monitoring",
            "infiniband",
            "rdma",
            "nvlink",
            "multi-node training",
            "slurm",
        ],
        "description": "Provision and optimize the GPU infrastructure that trains frontier AI.",
        "tools": ["SLURM", "Kubernetes", "CUDA", "Prometheus", "Grafana"],
        "certifications": ["NVIDIA DGX Certified", "CKA", "AWS ML Specialty"],
    },
]

# ─── 110+ Skills Master List ────────────────────────────────────────────────
ALL_SKILLS = sorted(
    list(
        set(
            [
                # Programming
                "python",
                "javascript",
                "typescript",
                "java",
                "c++",
                "c",
                "c#",
                "rust",
                "go",
                "golang",
                "scala",
                "r",
                "julia",
                "swift",
                "kotlin",
                "dart",
                "ruby",
                "php",
                "bash",
                "matlab",
                # ML / AI
                "machine learning",
                "deep learning",
                "nlp",
                "computer vision",
                "reinforcement learning",
                "statistics",
                "mathematics",
                "linear algebra",
                "probability",
                "bayesian statistics",
                "feature engineering",
                "model evaluation",
                "time series",
                "forecasting",
                "anomaly detection",
                "causal inference",
                "generative models",
                "diffusion models",
                "gan",
                "transformers",
                # Frameworks
                "tensorflow",
                "pytorch",
                "scikit-learn",
                "keras",
                "huggingface",
                "langchain",
                "llm",
                "rag",
                "prompt engineering",
                "llama index",
                "langsmith",
                "openai",
                "anthropic",
                "jax",
                "flax",
                "paddle",
                "mxnet",
                "onnx",
                "triton",
                "cuda",
                "tensorrt",
                # Data
                "sql",
                "nosql",
                "pandas",
                "numpy",
                "spark",
                "hadoop",
                "kafka",
                "flink",
                "airflow",
                "dbt",
                "snowflake",
                "bigquery",
                "redshift",
                "databricks",
                "delta lake",
                "duckdb",
                "elasticsearch",
                "mongodb",
                "postgresql",
                "mysql",
                "redis",
                "cassandra",
                "neo4j",
                # Cloud & DevOps
                "aws",
                "azure",
                "gcp",
                "docker",
                "kubernetes",
                "terraform",
                "ansible",
                "helm",
                "ci/cd",
                "git",
                "linux",
                "bash",
                "networking",
                "security",
                "monitoring",
                "observability",
                "prometheus",
                "grafana",
                "opentelemetry",
                "argo cd",
                "github actions",
                "jenkins",
                # Frontend
                "react",
                "nextjs",
                "vue.js",
                "angular",
                "svelte",
                "html",
                "css",
                "tailwind css",
                "figma",
                "ui/ux",
                "accessibility",
                "web performance",
                "webpack",
                "vite",
                "storybook",
                # Backend
                "rest api",
                "graphql",
                "grpc",
                "microservices",
                "message queues",
                "caching",
                "fastapi",
                "django",
                "flask",
                "spring boot",
                "express",
                "node.js",
                "actix",
                "gin",
                "fiber",
                # Other
                "mlops",
                "mlflow",
                "data pipelines",
                "etl",
                "data warehouse",
                "data lake",
                "knowledge graphs",
                "vector databases",
                "pinecone",
                "weaviate",
                "qdrant",
                "iot",
                "embedded systems",
                "ros",
                "robotics",
                "computer vision",
                "slam",
                "blockchain",
                "solidity",
                "web3",
                "smart contracts",
                "cryptography",
                "product management",
                "agile",
                "scrum",
                "leadership",
                "technical writing",
                "data governance",
                "compliance",
                "privacy",
                "gdpr",
                "hipaa",
                "penetration testing",
                "ethical hacking",
                "zero trust",
                "devsecops",
                "soc",
                "incident response",
                "mobile development",
                "react native",
                "flutter",
                "swiftui",
                "jetpack compose",
                "unity",
                "unreal engine",
                "vr/ar",
                "spatial computing",
                "edge computing",
                "quantum computing",
                "digital twin",
                "simulation",
                "federated learning",
            ]
        )
    )
)

CATEGORIES = sorted(list(set(r["category"] for r in JOB_ROLES_DB)))
